<?php

namespace Amp\Http\Server\Session;

interface IdGenerator
{
    /**
     * @return string A URL-safe session ID.
     */
    public function generate(): string;

    /**
     * Determines if the given ID could have been generated by this generator.
     */
    public function validate(string $id): bool;
}
